### ISSUE TITLE
out of focas on tetra league, while playing.

### ISSUE THREAD

**Issue by Rosalia-m** [o5k/tetrio-issues#1293] opened 2024-04-27 08:13 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Google chrome

### Describe the bug/issue

while playing in the tetra league, my mouse in on the game screen, like not on the chat or on another part of the screen, where if accidentally pressed would cause the out-of-focus message to pop up. it just randomly pops up and Its not letting me get out of it when I press the game, like to get it off I have to press the chat then press esc. it caused me to lose several of my games. it happened in every game both in the tetra league and in quick play, some I got lucky and I managed to get back to gameplay and win but a lot of the times it causes me to lose those games. in the last tetra league game it happened twice and caused me to lose 2 of the 5 games which I think is unfair because sometimes it happens when its a longer game so the pieces go faster. when they go faster its easier to lose before I can get out of it. I'm not denying that I lost fair and square, I did lose 3 of those games because I was worse but those 2 games I had a chance to clear them but could not because of that out of focas message.

### Expected behavior

the game play should not go "out of focas" if I'm in the middle of playing without my mouse pressing another screen or the chat box. like if my mouse is over my board it should not be going "out of focas" and when if it does it should be like the other times where you can get out of it by pressing your board.

**Comment by ZaptorZap** [comment] 2024-04-27 08:17
Duplicate of #994

**Closed as not planned by ZaptorZap** 2024-04-27 08:17 UTC
Labels: bug, duplicate
