### ISSUE TITLE
The google ad sometimes blocks what piece i have on hold and I cannot see my stats either in ranked

### ISSUE THREAD

**Issue by kyly6900** [o5k/tetrio-issues#1320] opened 2024-07-12 13:23 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

macOS Monterey 12.7.5

### Browser and version

Chrome (latest version??)

### Describe the bug/issue

I was playing ranked tetrio and the google advertistment was blocking the view of what piece i had on hold. I nearly lost my ranked match because of it 

### Expected behavior

The ad should be the usual long one that blocks some of the chat but not the actual holding piece.

**Comment by ZaptorZap** [comment] 2024-07-12 13:29
Duplicate of https://github.com/tetrio/issues/issues/1122

**Closed as not planned by ZaptorZap** 2024-07-12 13:29 UTC
Labels: bug, duplicate
