### ISSUE TITLE
Get tablet support or mobile support

### ISSUE THREAD

**Issue by SillyHenryontetris** [o5k/tetrio-issues#1368] opened 2024-08-20 09:44 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

Yes this is a problem i want to plat tetrio on my tablet

### Describe the solution you'd like

Buttons like left ,right ,soft drop,hard drop,rotate clockwise or counter clockwise,180 rotate and hold

### Describe alternatives you've considered
Osk i know it's hard for you
### Additional context

Nothing just buttons pls

**Comment by SillyHenryontetris** [comment] 2024-08-20 09:46
I don't kNow how to use **gifhub**

**Comment by ZaptorZap** [comment] 2024-08-20 09:55
Duplicate of https://github.com/tetrio/issues/issues/950

**Closed as not planned by ZaptorZap** 2024-08-20 09:55 UTC
Labels: improvement, duplicate
