### ISSUE TITLE
Out of focus while actively playing tetr.io

### ISSUE THREAD

**Issue by Spectrum3563** [o5k/tetrio-issues#1313] opened 2024-06-25 07:43 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Chrome 126.0.6478.126

### Describe the bug/issue

I got "Out of focus" while playing tetr.io. I did not misclick out side, just using the keyboard normally.

### Reproducing

"Out of focus" warn while playing

### Expected behavior

I expected it works normally

**Comment by ZaptorZap** [comment] 2024-06-25 07:44
Duplicate of #994

**Closed as not planned by ZaptorZap** 2024-06-25 07:44 UTC
Labels: bug, duplicate

**Comment by Spectrum3563** [comment] 2024-07-08 11:58
> Duplicate of #994

I tried pressing the stuck key, but it still drag the pieces on its way, until i start a new match
