### ISSUE TITLE
tetra league, desktop client,  "out of focus" in game

### ISSUE THREAD

**Issue by quackadillyblip** [o5k/tetrio-issues#1384] opened 2024-09-09 08:01 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

windows 11

### Browser and version

1.2.4

### Describe the bug/issue

game loses focus during game in vs mode

### Reproducing

open desktop client
start match up
play

### Expected behavior

not to lose focus when ads pop up

### Additional context

other issues reported the same bug in browser, not in desktop client

**Comment by quackadillyblip** [comment] 2024-09-09 11:09
game has become unplayable

too bad
hope you guys be able to fix this

**Comment by ZaptorZap** [comment] 2024-09-09 19:15
Duplicate of https://github.com/tetrio/issues/issues/994

**Closed as not planned by ZaptorZap** 2024-09-09 19:15 UTC
Labels: bug, duplicate
