### ISSUE TITLE
WEBGL crash while updating to V9

### ISSUE THREAD

**Issue by Missdrop** [o5k/tetrio-issues#1272] opened 2024-03-12 15:22 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Arch Linux

### Browser and version

TETR.IO Desktop V9

### Describe the bug/issue

it can be happened everywhere while using Desktop V9
may be a electron issue or not
I run it in terminal so that you can see logs below

### Reproducing

play for a while

### Expected behavior

never crash again

### Screenshots

![image](https://github.com/tetrio/issues/assets/101849047/75cd9168-3689-4892-b389-08950e683acc)

### Console logs

─ /opt/TETR.IO/TETR.IO 
Gtk-Message: 23:09:25.383: Failed to load module "appmenu-gtk-module"
[10490:0312/231053.970849:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[10490:0312/231241.214894:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[10490:0312/231321.625308:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[10738:0312/231322.228173:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[10490:0312/231322.228500:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[10983:0312/231322.443935:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[10738:0312/231322.444746:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[10490:0312/231322.929520:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[10490:0312/231323.661502:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[10738:0312/231324.421552:ERROR:command_buffer_proxy_impl.cc(323)] GPU state invalid after WaitForGetOffsetInRange.
[10490:0312/231324.422316:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[10490:0312/231324.893782:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[10490:0312/231325.257841:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[10490:0312/231325.672246:ERROR:gpu_process_host.cc(989)] GPU process exited unexpectedly: exit_code=133
[10490:0312/231325.672308:FATAL:gpu_data_manager_impl_private.cc(448)] GPU process isn't usable. Goodbye.
[1]    10490 trace trap (core dumped)  /opt/TETR.IO/TETR.IO

### Additional context

never happened on V8 and before. maybe i should downgrade back to v8 and wait

**Comment by visiblyisabelle** [comment] 2024-03-12 15:29
looks like a dupe of #1268

**Closed as completed by visiblyisabelle** 2024-03-12 15:29 UTC
Labels: bug

**Comment by Missdrop** [comment] 2024-03-12 15:34
> looks like a dupe of #1268 

but i'm sure it caused by the electron update, not changing settings because it can be happened everywhere

**Comment by visiblyisabelle** [comment] 2024-03-12 15:36
lots of interface elements have tooltips, not just the config menu. in any case, the problems are so similar that it's best to consolidate it into one issue.

**Comment by Missdrop** [comment] 2024-03-12 15:38
> lots of interface elements have tooltips, not just the config menu. in any case, the problems are so similar that it's best to consolidate it into one issue.

I agree
