### ISSUE TITLE
desktop client has lag when tetra league

### ISSUE THREAD

**Issue by wonsunil** [o5k/tetrio-issues#1383] opened 2024-09-08 09:27 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

windows 10

### Browser and version

1.2.3 production

### Describe the bug/issue

//I used a translator, so the content may not be accurate.

When I enter into tetra league, I see a banner ad on the right and intermittently get internet delays, foucs out event along with ad updates.

### Reproducing

1. go to multiplayer > tetra league > enter match

### Expected behavior

This phenomenon was seen more in urgent situations, and in nearly 20 days of games, focus out occurred once or twice per game

**Comment by ZaptorZap** [comment] 2024-09-09 19:16
Duplicate of https://github.com/tetrio/issues/issues/994

**Closed as not planned by ZaptorZap** 2024-09-09 19:16 UTC
Labels: bug
