### ISSUE TITLE
Not at 7-bag in ranked?

### ISSUE THREAD

**Issue by nate628426** [o5k/tetrio-issues#1295] opened 2024-04-28 01:38 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

MacOS

### Browser and version

MacOS Desktop version (Silicon)

### Describe the bug/issue

I feel I encountered a glitch in my bag while playing ranked tetrio. I think I did not have a 7-bag from the start. 

### Reproducing

Unsure how to reproduce, first time encountering

### Expected behavior

I expect every available piece (7) to appear once before a new set of duplicates appear.

### Screenshots

<img width="1202" alt="Screenshot 2024-04-27 at 9 35 10 PM" src="https://github.com/tetrio/issues/assets/58781334/44285e1d-c539-4bb1-81f6-28dab6bbe1f4">
<img width="1194" alt="Screenshot 2024-04-27 at 9 37 40 PM" src="https://github.com/tetrio/issues/assets/58781334/3d829406-58b5-4c0a-8b5f-378f3d2dcc73">

### Additional context

Unsure what happened or I'm having a mental lapse here, but I think I encountered a bug with how the bag is supposed to spawn pieces. I also just got into S-, is the bag different in S- above compared to A+ and below?

**Comment by ZaptorZap** [comment] 2024-04-28 01:40
Duplicate of #1294

**Closed as not planned by ZaptorZap** 2024-04-28 01:40 UTC
Labels: bug, duplicate
