### ISSUE TITLE
Ability to spectate on going matches

### ISSUE THREAD

**Issue by Founntain** [o5k/tetrio-issues#355] opened 2020-06-06 18:22 UTC
### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
It would be a neat addition to the game, if you could spectate games, when they're currently in progress. As an example: If I join a custom room, I would like to spectate the ongoing match, instead of sitting around and not be able to see at least when the game would end.
Also good to mention is, that it is much better, to spectate people, then starring on the lobby screen.

### Solution Methods
First Solution: You get always enforced to spectate the ongoing match.
Second Solution: Add an Spectate on going match button somewhere in the lobby, to start spectating the ongoing match.

**Comment by ZaptorZap** [comment] 2020-06-06 19:00
Hey there Founntain, I'm afraid this has been suggested again and again, and trust me it's a planned feature. Blog posts and the relevant quotes below: 
[44 Fact Frenzy](https://blog.osk.sh/post.php?p=5df9463f716867.05060790)
> 13. Planned for later: Spectate in-progress matches | Planned for later
> When our code is ready for it, we hope to allow you to spectate games that are already in progress!

[Alpha Release](https://blog.osk.sh/post.php?p=5e76725469c492.94375614)
> It's impossible to spectate a match that's already begun right now. I'd like to make it possible to do so - it just requires a bit of headache code-wise.

**Comment by Founntain** [comment] 2020-06-06 19:11
Thanks for letting me know. I just looked in the Issues if this is posted here somewhere. But great to hear that this is already on the To-Do List.

**Comment by o5k** [comment] 2020-06-08 17:08
Duplicate of #341

**Closed by o5k** 2020-06-08 17:08 UTC
Labels: improvement
