### ISSUE TITLE
Damage setting for Perfect Clear in multiplayer rooms

### ISSUE THREAD

**Issue by Euclid123** [o5k/tetrio-issues#1319] opened 2024-07-10 02:08 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I play casually in multiplayer mode and I am not a fan of those kill openers ruining the experience.  I would like to mess around without being killed in the first 10 seconds.  I know how to deal with openers but in this casual mode, I would rather build stupid things to amuse myself and exchange attacks.  Think of it as 'less tryhard'.  They are fine in Tetra League, a mode I do not play. 

I define a kill opener as something that's looping perfect clears (PCs).  Something like SDPC>DPC>MS2>PC>DPC and the such.
I define 'let me play' as being able to play for at least 30 seconds in a match.

### Describe the solution you'd like

Introduce a setting in multiplayer rooms to set the amount of garbage sent by PCs.  
There is an option to turn PCs off, but that is not fun. 
I suggest 0-20, standard is 10 lines.  Allowing users to set it higher can also be pretty funny with those clean garbage or one-line progression garbage settings. 

### Describe alternatives you've considered

As stated, I can just disable PCs altogether but that changes the game far too much.

**Comment by ZaptorZap** [comment] 2024-07-10 02:21
Duplicate of #731

**Closed as not planned by ZaptorZap** 2024-07-10 02:21 UTC
Labels: improvement, duplicate
