### ISSUE TITLE
The exit button seems to be missing when spectating matches.

### ISSUE THREAD

**Issue by themanthemyth717** [o5k/tetrio-issues#1333] opened 2024-07-27 22:12 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

windows 10

### Browser and version

Chrome 125.0.6422.61

### Describe the bug/issue

The exit button seems to be missing when you spectate a lobby in the room listing. When I play in an lobby from room listing, and lose, there is no exit button so I am forced to spectate until the match is over, or just close the game and open it back up. 

### Reproducing

When you first get on the game and log in, go to multiplayer, and room listing. Select any room, and then press spectate. Once you are there, you should notice that the exit button is missing. 

### Expected behavior

I am supposed to be able to press the exit button while spectating, or use the esc shortcut to return to the lobby.

### Screenshots

![image](https://github.com/user-attachments/assets/666b2aed-b4fa-441b-9c27-ba0831fee49c)

**Comment by WoktopusGaming** [comment] 2024-07-27 22:15
oh sorry, i've already made a report on that... #1332

**Comment by ZaptorZap** [comment] 2024-07-27 22:44
Duplicate of #1332

**Closed as not planned by ZaptorZap** 2024-07-27 22:44 UTC
Labels: bug, duplicate
