### ISSUE TITLE
Dying with a stock causes the red to not go away?

### ISSUE THREAD

**Issue by Neeko-iko** [o5k/tetrio-issues#243] opened 2020-04-08 16:50 UTC
### Describe the bug/issue
after losing a stock the board didn't properly reset its colors from "danger"

### Reproducing
1. Go to custom lobby (assumedly with multiple people? i had 4 other people with me)
2. have at least 1 stock
3. die

### Expected behavior
The board should go back to being all white no reds

### Screenshots
![image](https://user-images.githubusercontent.com/45524401/78810966-f9615580-797d-11ea-810e-7ab480269dff.png)

### Your setup
 - OS: Windows 10
 - Browser:  Chromium Edge 80.0.361.111

**Comment by Neeko-iko** [comment] 2020-04-08 16:52
the image may be a bad example but even after the tetris the red stayed

**Comment by o5k** [comment] 2020-04-09 19:07
Cannot reproduce?

**Comment by o5k** [comment] 2020-04-30 00:47
Duplicate of #253

**Closed by o5k** 2020-04-30 00:47 UTC
Labels: bug, feat: engine, needs-info
