### ISSUE TITLE
Final time is different ingame and in result screen

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#49] opened 2020-02-18 21:39 UTC
### Description
Final time shown is different from final time shown ingame.

### Reproduction
- Create custom game with "Topping out is OK", with stopwatch shown and with time shown in the end screen
- Top out

### Expected behavior
Time ingame during top out should match time in the result screen.

### Screenshots
![image](https://user-images.githubusercontent.com/6901295/74780114-d75d2800-5296-11ea-8f35-1f815f5dbdbd.png)
![image](https://user-images.githubusercontent.com/6901295/74780138-e5ab4400-5296-11ea-9f1c-a68c21d54443.png)

### Your setup
Arch Linux 5.5.4-arch1-1 on x86_64 PC, using Firefox 73.0

**Comment by o5k** [comment] 2020-02-25 23:11
Fixed in next patch.

**Closed by o5k** 2020-02-25 23:11 UTC
Labels: bug

**Comment by Wirtualnosc** [comment] 2020-03-09 22:31
Still happens, but not in custom games (I suppose that's because of server verification?). Had a 40L game of 1:10.383 (as seen in result screen), but ingame the final time shown was 1:10.400. Not sure if this is easily fixable.

**Comment by o5k** [comment] 2020-03-10 09:25
Oooh, actually that's probably a regression caused by fixing #98 . Will reopen that
