### ISSUE TITLE
out of focus

### ISSUE THREAD

**Issue by Samsaaam** [o5k/tetrio-issues#1346] opened 2024-08-01 02:24 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Brave

### Describe the bug/issue

In the new multiplayer game mode, quick play, i've been having this problem where the game thinks im out of focus, aka i've somehow clicked outside the game window, which is not the case and i cant enjoy a long game of quickplay. Sometime it lets me come back to the game when i click back on the game mode, sometimes not.

### Reproducing

1. start a quickplay game
2. play 
3. until it says "out of focus" out of nowhere

### Expected behavior

Lost of control in the game mode quick play, making pieces falling in the middle, without any way of coming back

### Screenshots

![Screenshot 2024-07-31 222307](https://github.com/user-attachments/assets/d165d602-889a-429b-a461-5eb4299cfff4)

### Console logs

(function anonymous(
) {
debugger
})

**Comment by BunBunWeens** [comment] 2024-08-03 22:31
One thing I've noticed is that it triggers for me when ever a new ad is displayed, not sure if that is one of the things causing it or if it is a coincidence

**Comment by CodeObserver21** [comment] 2024-08-04 00:52
I have the same issue on desktop clients for both Debian 12 and openSUSE Leap 15.6. It does seem to occur whenever a new ad is displayed.

**Comment by MatthewNichols80** [comment] 2024-08-04 20:19
Ive had the same issue in quick play with the desktop app version, it goes out of focus when a new ad pops up

**Comment by WillitDoesMusic** [comment] 2024-08-10 13:50
> One thing I've noticed is that it triggers for me when ever a new ad is displayed, not sure if that is one of the things causing it or if it is a coincidence

How do I fix this

**Comment by ZaptorZap** [comment] 2024-08-11 06:37
Duplicate of #994

**Closed as not planned by ZaptorZap** 2024-08-11 06:37 UTC
Labels: bug, duplicate
