### ISSUE TITLE
"Hotfix" for not being able to spectate ongoing games

### ISSUE THREAD

**Issue by LayneTheEpic** [o5k/tetrio-issues#319] opened 2020-05-13 22:21 UTC
Currently, the game just displays "Quick Play - Good luck!" or the room settings menu while ingame. If you could add a small widget that displays how many people are left that'd be nice. Later once you can hop into the ongoing game this can be removed.

**Comment by csq-curiosity** [comment] 2020-05-14 06:27
Duplicate of #202. This one's a little more comprehensive in that it also includes game time, and score counts for FT2+ games.

**Comment by LayneTheEpic** [comment] 2020-05-14 14:50
I see, thanks for letting me know, I'll probably close this issue

**Closed** 2020-05-14 14:50 UTC
Labels: improvement
