### ISSUE TITLE
Tie Game Settings to Each Account

### ISSUE THREAD

**Issue by DanKruse731** [o5k/tetrio-issues#270] opened 2020-04-17 18:06 UTC
### Situations
Whenever I change computers or an update occurs, I am forced to set my controls manually every time. This gets annoying real fast.

### Solution
Save control bindings and settings and tie them to each account similar to Jstris.

**Comment by o5k** [comment] 2020-04-19 14:20
Duplicate of #7

**Closed by o5k** 2020-04-19 14:20 UTC
Labels: improvement
