### ISSUE TITLE
Ads forcing out of focus

### ISSUE THREAD

**Issue by PrairieD0g** [o5k/tetrio-issues#1380] opened 2024-09-05 01:37 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Microsoft edge

### Describe the bug/issue

Ads in the 2 minute blitz will change and force you out of focus playing the desktop version.  Also seem to have lowered frame rate

### Expected behavior

One would expect no drops in frame rate. Ads should not force the player out of focus

**Comment by ZaptorZap** [comment] 2024-09-05 07:36
Duplicate of https://github.com/tetrio/issues/issues/994

**Closed as not planned by ZaptorZap** 2024-09-05 07:36 UTC
Labels: bug, duplicate
