### ISSUE TITLE
Ads popping up in the middle of play

### ISSUE THREAD

**Issue by MattCrn20** [o5k/tetrio-issues#1348] opened 2024-08-01 16:57 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Opera GX 

### Describe the bug/issue

Hello there TETR.IO team. There is a bug that I have been experiencing with the new quickplay 2 mode. Sometimes, in the middle of play, a banner ad will pop up in the middle of the gameplay, making it difficult to see the upper half of the board, the hold queue, and the next 2 pieces in the next queue. I am currently not a TETR.IO supporter, meaning I do have ads on.

### Reproducing

1. go into quickplay 2
2. make sure you don't have TETR.IO supporter
3. play until the ad pops up

### Expected behavior

There shouldn't be a random ad that pops up in the middle of play. I have seen plenty of ads on the main menu which is to be expected, but never in the middle of play. I have been playing TETR.IO for a little over a year now, and this is the first time this has happened to me.

### Screenshots

![image_2024-08-01_124603999](https://github.com/user-attachments/assets/faf7e937-820a-42fd-aae5-d83d909fcbec)

This is only one example of this happening. Sometimes, the ad will be a lot bigger, making seeing the board even harder.

### Console logs

bootstrap.js?hv=7d033e49.1cd747269f35.60000aa2f8ff:2 Bootstrapping for hardver 7d033e49.1cd747269f35.60000aa2f8ff
VM13:34 webgl backend was already registered. Reusing existing backend factory.
t.registerBackend @ VM13:34
VM13:34 cpu backend was already registered. Reusing existing backend factory.
t.registerBackend @ VM13:34
VM13:34 Platform browser has already been set. Overwriting the platform with [object Object].
t.setPlatform @ VM13:34
VM13:56 TETR.IO
VM13:56 Please be careful when pasting anything in the console. Attackers may be out to steal your login information.
VM13:56 Using the Desktop Client
VM13:56 Up to date. Local version 1.0.1-production | Commit 7d033e49@master (7/30/2024, 8:12:13 PM) | Server cycle 1cd747269f35 | Build 60000aa2f8ff (7/30/2024, 8:25:21 PM)
VM13:56 Loading Ceriad provider...
VM13:56 GTM loaded.
VM13:56 RAMP loaded.
VM13:56 fun-hooks: referenced 'adpod' but it was never created
window.console.warn @ VM13:56
VM13:56 Ceriad provider launched.
VM13:56 [GPT] Attempted to load GPT multiple times.
https://goo.gle/gpt-message#152
window.console.warn @ VM13:56
VM13:56 menus-persistent-mpu mounted, now 1 mounts
VM13:56 PixiJS 6.1.3 - WebGL 2
VM13:56 - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tetrio-desktop/9.0.0 Chrome/122.0.6261.70 Electron/29.1.0 Safari/537.36 -CPU: 8-coreMemory: ~8 GBConnection: 6.05 Mbps, 150ms RTT [4g]
VM13:56 Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 (0x00003E9B) Direct3D11 vs_5_0 ps_5_0, D3D11)
VM13:56 InitialConnect > Obtaining Ribbon endpoint...
VM13:56 InitialConnect > Obtained Ribbon endpoint /ribbon/imamiya and 26 spools, fallback available.
VM13:56 InitialConnect > Getting a spool...
VM13:56 InitialConnect > Spool > Spooling started
VM13:56 InitialConnect > Spool >    20+40ms na-east-kurisu [US] v4 // 0.0625, 0.046875, 0.015625
VM13:56 InitialConnect > Spool >    20+47ms na-mid-maho [CA] v4 // 0.078125, 0.046875, 0
VM13:56 InitialConnect > Spool >    27+53ms na-east-mayuri [US] v4 // 0.09375, 0.0625, 0.03125
VM13:56 InitialConnect > Spool > Spooled na-east-kurisu!
VM13:56 InitialConnect > Obtained spool na-east-kurisu (na-east-kurisu.spool.tetr.io) [US].
sync.search.spotxchange.com/partner?adv_id=7715&uid=3260868765218809044:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
sync.extend.tv/r.gif?exchange=liveramp&ZUID=3260868765218809044:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
rtb2-useast.e-volution.ai/sync?exchange=262&r=https%3A%2F%2Fsync.e-volution.ai%2Fd155ae938e60a3962c32b17879e8586f.gif%3Fpuid%3D%5BUID%5D:1 
        
        
       Failed to load resource: the server responded with a status of 400 (Bad Request)
farm.plista.com/matching/pixel/?ssp=c3de&dsp_user_id=3260868765218809044:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
usersync:1 
        
        
       Failed to load resource: the server responded with a status of 400 ()
 Powered by AMP ⚡ HTML – Version 2406241625000 https://tetr.io/
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 menus-persistent-mpu mounted, now 1 mounts
VM13:56 zenith-persistent-mpu mounted, now 2 mounts
VM13:56 menus-persistent-mpu unmounted, now 1 mounts
VM13:56 menus-persistent-mpu mounted, now 2 mounts
VM13:56 Tyche Warning: Found more than 1 slots of type: med_rect, pos: ATF.
window.console.warn @ VM13:56
VM13:56 zenith-persistent-mpu unmounted, now 1 mounts
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 menus-persistent-mpu mounted, now 1 mounts
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 menus-persistent-mpu mounted, now 1 mounts
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 menus-persistent-mpu mounted, now 1 mounts
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 menus-persistent-mpu mounted, now 1 mounts
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 menus-persistent-mpu mounted, now 1 mounts
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 menus-persistent-mpu mounted, now 1 mounts
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 menus-persistent-mpu mounted, now 1 mounts
VM13:56 zenith-persistent-mpu mounted, now 2 mounts
VM13:56 menus-persistent-mpu unmounted, now 1 mounts
 a: 0.005126953125 ms
VM13:56 AmbientRespool > Starting ambient respool.
VM13:56 AmbientRespool > Obtaining Ribbon endpoint...
VM13:56 AmbientRespool > Obtained Ribbon endpoint /ribbon/gil and 26 spools, fallback available.
VM13:56 AmbientRespool > Getting a spool...
VM13:56 AmbientRespool > Spool > Spooling started
VM13:56 AmbientRespool > Spool >   216+40ms na-east-kurisu [US] v4 // 0.0625, 0.0625, 0.015625
VM13:56 AmbientRespool > Spool > Spooled na-east-kurisu!
VM13:56 AmbientRespool > Obtained spool na-east-kurisu (na-east-kurisu.spool.tetr.io) [US].
VM13:56 AmbientRespool > Obtained new token, already on best available spool.
VM13:56 menus-persistent-mpu mounted, now 2 mounts
VM13:56 Tyche Warning: Found more than 1 slots of type: med_rect, pos: ATF.
window.console.warn @ VM13:56
VM13:56 zenith-persistent-mpu unmounted, now 1 mounts
VM13:56 zenith-persistent-mpu mounted, now 2 mounts
VM13:56 menus-persistent-mpu unmounted, now 1 mounts
 a: 0.0009765625 ms
 Powered by AMP ⚡ HTML – Version 2406241625000 https://tetr.io/
s.thebrighttag.com/csx?tp=an&uid=3260868765218809044:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
sync.jivox.com/tags/sync/usync.php?px=guSgCl60&puid=3260868765218809044:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
4 Powered by AMP ⚡ HTML – Version 2406241625000 https://tetr.io/
sync.taboola.com/sg/xndr/1/cm?adnxs_uid=3260868765218809044&gdpr=0&gdpr_consent=:1 
        
        
       Failed to load resource: the server responded with a status of 400 ()
cookies.andbeyond.media/1f197a5d9efb6d849433724bb397beb3.gif?puid=3260868765218809044&redir=:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
 a: 0.0009765625 ms
 a: 0.001953125 ms
VM13:56 AmbientRespool > Starting ambient respool.
VM13:56 AmbientRespool > Obtaining Ribbon endpoint...
VM13:56 AmbientRespool > Obtained Ribbon endpoint /ribbon/gil and 26 spools, fallback available.
VM13:56 AmbientRespool > Getting a spool...
VM13:56 AmbientRespool > Spool > Spooling started
VM13:56 AmbientRespool > Spool >    69+41ms na-east-kurisu [US] v4 // 0.015625, 0.046875, 0
VM13:56 AmbientRespool > Spool >   111+47ms na-mid-maho [CA] v4 // 0.078125, 0.078125, 0
VM13:56 AmbientRespool > Spool >   136+53ms na-east-mayuri [US] v4 // 0.015625, 0.046875, 0.03125
VM13:56 AmbientRespool > Spool > Spooled na-east-mayuri!
VM13:56 AmbientRespool > Obtained spool na-east-mayuri (na-east-mayuri.spool.tetr.io) [US].
VM13:56 AmbientRespool > Obtained new token, no significant ping advantage 119ms → 377ms.
4 a: 0.0009765625 ms
VM13:56 Uncaught TypeError: Cannot read properties of null (reading 'removeChild')
    at eval (eval at <anonymous> (bootstrap.js?hv=7d033e49.1cd747269f35.60000aa2f8ff:1:1), <anonymous>:56:428130)
VM13:56 menus-persistent-mpu mounted, now 2 mounts
VM13:56 Tyche Warning: Found more than 1 slots of type: med_rect, pos: ATF.
window.console.warn @ VM13:56
VM13:56 zenith-persistent-mpu unmounted, now 1 mounts
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 menus-persistent-mpu mounted, now 1 mounts
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 AmbientRespool > Starting ambient respool.
VM13:56 AmbientRespool > Obtaining Ribbon endpoint...
VM13:56 AmbientRespool > Obtained Ribbon endpoint /ribbon/shizuru and 26 spools, fallback available.
VM13:56 AmbientRespool > Getting a spool...
VM13:56 AmbientRespool > Spool > Spooling started
VM13:56 AmbientRespool > Spool >    35+40ms na-east-kurisu [US] v4 // 0.015625, 0.046875, 0
VM13:56 AmbientRespool > Spool > Spooled na-east-kurisu!
VM13:56 AmbientRespool > Obtained spool na-east-kurisu (na-east-kurisu.spool.tetr.io) [US].
VM13:56 AmbientRespool > Obtained new token, already on best available spool.
VM13:56 menus-persistent-mpu mounted, now 1 mounts
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 menus-persistent-mpu mounted, now 1 mounts
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 menus-persistent-mpu mounted, now 1 mounts
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 menus-persistent-mpu mounted, now 1 mounts
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 menus-persistent-mpu mounted, now 1 mounts
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 menus-persistent-mpu mounted, now 1 mounts
 a: 0.005859375 ms
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 menus-persistent-mpu mounted, now 1 mounts
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 menus-persistent-mpu mounted, now 1 mounts
 a: 0.0029296875 ms
 a: 0.002197265625 ms
 a: 0.0029296875 ms
 a: 0.00390625 ms
3 a: 0.001953125 ms
 a: 0.007080078125 ms
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 menus-persistent-mpu mounted, now 1 mounts
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 menus-persistent-mpu mounted, now 1 mounts
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 menus-persistent-mpu mounted, now 1 mounts
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 menus-persistent-mpu mounted, now 1 mounts
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 menus-persistent-mpu mounted, now 1 mounts
VM13:56 zenith-persistent-mpu mounted, now 2 mounts
VM13:56 menus-persistent-mpu unmounted, now 1 mounts
VM13:56 AmbientRespool > Starting ambient respool.
VM13:56 AmbientRespool > Obtaining Ribbon endpoint...
VM13:56 AmbientRespool > Obtained Ribbon endpoint /ribbon/inoue and 26 spools, fallback available.
VM13:56 AmbientRespool > Getting a spool...
VM13:56 AmbientRespool > Spool > Spooling started
VM13:56 AmbientRespool > Spool >   238+40ms na-east-kurisu [US] v4 // 0.046875, 0.046875, 0
VM13:56 AmbientRespool > Spool >   239+0ms eu-mikoto [NL] v4 // 0.125, 0.125, 0.09375
VM13:56 AmbientRespool > Spool >   239+71ms na-west-agiri [US] v4 // 0.015625, 0.03125, 0
VM13:56 AmbientRespool > Spool > Spooled na-west-agiri!
VM13:56 AmbientRespool > Obtained spool na-west-agiri (na-west-agiri.spool.tetr.io) [US].
VM13:56 AmbientRespool > Obtained new token, no significant ping advantage 175ms → 619ms.
 a: 0.001953125 ms
ad.doubleclick.net/d…11;rcsrc=h;prcl=s:1 Uncaught (in promise) TypeError: Failed to fetch
 a: 0.001953125 ms
3 Powered by AMP ⚡ HTML – Version 2406241625000 https://tetr.io/
 a: 0.001953125 ms
 a: 0.0029296875 ms
 a: 0.001953125 ms
1003Third-party cookie will be blocked. Learn more in the Issues tab.
 a: 0.001953125 ms
VM13:56 menus-persistent-mpu mounted, now 2 mounts
VM13:56 Tyche Warning: Found more than 1 slots of type: med_rect, pos: ATF.
window.console.warn @ VM13:56
VM13:56 zenith-persistent-mpu unmounted, now 1 mounts
2 Powered by AMP ⚡ HTML – Version 2406241625000 https://tetr.io/
14The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
htlb.casalemedia.com/openrtb/pbjs?s=1030980:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_CLOSED
htlb.casalemedia.com/openrtb/pbjs?s=1030980:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_CLOSED
VM13:56 AmbientRespool > Starting ambient respool.
VM13:56 AmbientRespool > Obtaining Ribbon endpoint...
VM13:56 AmbientRespool > Obtained Ribbon endpoint /ribbon/lucia and 26 spools, fallback available.
VM13:56 AmbientRespool > Getting a spool...
VM13:56 AmbientRespool > Spool > Spooling started
VM13:56 AmbientRespool > Spool >   164+40ms na-east-kurisu [US] v4 // 0.046875, 0.03125, 0
VM13:56 AmbientRespool > Spool > Spooled na-east-kurisu!
VM13:56 AmbientRespool > Obtained spool na-east-kurisu (na-east-kurisu.spool.tetr.io) [US].
VM13:56 AmbientRespool > Obtained new token, already on best available spool.
 a: 0.00390625 ms
VM13:56 menus-persistent-mpu unmounted, now 0 mounts
VM13:56 menus-persistent-mpu mounted, now 1 mounts
cookie_syn:1 
        
        
       Failed to load resource: the server responded with a status of 502 ()
usersync:1 
        
        
       Failed to load resource: the server responded with a status of 400 ()
9881 log entries are not shown.

### Additional context

I'm normally not someone to report a bug or whatever, but its starting to get a bit annoying, and i was just wondering if you guys could look into it.

Thanks
- MattCrn20

**Comment by ZaptorZap** [comment] 2024-08-01 16:58
Duplicate of https://github.com/tetrio/issues/issues/1122

**Closed as not planned by ZaptorZap** 2024-08-01 16:58 UTC
Labels: bug, duplicate
