### ISSUE TITLE
Crashes when trying to use the desktop version on Kubuntu 23.10

### ISSUE THREAD

**Issue by miguelthemann** [o5k/tetrio-issues#1300] opened 2024-05-17 11:42 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Kubuntu 23.10 

### Browser and version

TETR.IO Desktop 9 (v6.4.6-production when pressing F8)

### Describe the bug/issue

Whenever I try to play the game or browse the game settings, the game window goes black and closes or throws a WebGL crash error and closes shortly after. Happens when in the TETR.IO Desktop settings submenus especially. Works fine on Chrome 125.0.6422.60 64-bit.

### Reproducing

1. Open TETR.IO Desktop (Sometimes crashes just after opening too)
2. Open the settings
3. Wait ~12 seconds or browse a few submenus

### Expected behavior

Not crashing.

### Screenshots

![image](https://github.com/tetrio/issues/assets/88190875/15dbff59-4922-4179-8e7c-df7420c065f7)

### Additional context

I've tried multiple times to get the logs but the game crashes so I haven't really been able to. My system specifications are shown on the image. Everything is up to date and I have all drivers + codecs installed and up to date.
![image](https://github.com/tetrio/issues/assets/88190875/cba73187-cbad-4849-974b-fcdb1ca64683)

**Comment by visiblyisabelle** [comment] 2024-05-17 11:44
dupe of #1268

**Closed as not planned by visiblyisabelle** 2024-05-17 11:44 UTC
Labels: bug
