### ISSUE TITLE
My SFX

### ISSUE THREAD

**Issue by YaBudd** [o5k/tetrio-issues#1257] opened 2024-01-31 16:42 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

acer chromebook

### Browser and version

google

### Describe the bug/issue

Last morning, I was on **TETR.io** but when I joined it did not load . The game said it was loading SFX but I have been waiting for 2 weeks and there are no changes with this bug at all. I know it is not bad internet because i have tested my internet and it always said it was very fast.You might think it is because my laptop is old but that is not the cause as i have used it to play on there many times.

My  account and other information:
Account : AIDEN_XD
Number of times trying to load **TETR.io**: 173
Github Account: @Yabudd

Thanks Sincerely - AIDEN_XD

### Reproducing

I'm new to Github so IDK (I  Dont Know) how to reproduce.

### Expected behavior

I thought it would let me in normally but i guess not 😭 .

### Screenshots

I cannot take screen shots as i am on and old laptop.

### Console logs

it is the normal loading screen, but once you press join (or not :) )   on the bottom right corner of the screen just says "LOADING SFX".

### Additional context

IMa really big TETR.io fan so please help me .

**Comment by ZaptorZap** [comment] 2024-01-31 20:56
This issue report is ripe with errors...
Typically, this problem is caused by slow internet. We cannot make your internet faster. The game loads A-OK on my device(and many, many others as evidenced by analytics), so I'm closing this as invalid.

**Closed as not planned by ZaptorZap** 2024-01-31 20:56 UTC
Labels: bug, invałid

**Comment by YaBudd** [comment] 2024-02-06 15:44
But my Internet is very fast and its still not loading

**Comment by YaBudd** [comment] 2024-02-06 15:46
Please man, I beg you

**Comment by YaBudd** [comment] 2024-02-06 15:47
thanks,
