### ISSUE TITLE
Keybind Setting

### ISSUE THREAD

**Issue by Roxis88** [o5k/tetrio-issues#246] opened 2020-04-09 03:02 UTC
### Describe the bug/issue
It might be not a bug, but is the keybind not carry over with different PCs, even with the same account??
I'm using 2 different laptops, and when I change the keybind for 1 laptop, the other one still retain
the old keybind.

### Reproducing
1. Having 2 or more PCs.
2. Change the keybinds of one of the PCs, then close that PC.
3. See if the other PC will get the changed keybinds or not.

### Expected behavior
The keybind setting on one PC is different from others, even using the same account.

### Your setup
 - **OS and version**: Win 8 and Win 10
 - **Browser and version**:
Google Chrome Version 80.0.3987.163 (Official Build) (64-bit) - Win 8
Google Chrome Version 80.0.3987.163 (Official Build) (64-bit) - Win 10

**Comment by o5k** [comment] 2020-04-09 10:15
Duplicate of #7

**Closed by o5k** 2020-04-09 10:15 UTC
Labels: bug
