### ISSUE TITLE
Random lag spikes in multiplayer

### ISSUE THREAD

**Issue by mat1jaczyyy** [o5k/tetrio-issues#19] opened 2020-02-08 04:26 UTC
In multiplayer seemingly random lag spikes will appear where the game will process no inputs for roughly less than 0.5 seconds. Seems to be particularly notorious in matches with 4+ players. Other players such as Wumbotize have also noticed and complained about this

**Comment by o5k** [comment] 2020-02-08 20:34
For now, I'll be lowering the limit at which boards become "tiny". (There's 3 modes of display - `full`, which is what your own board, and the other player's board in a 1v1 renders as, `small`, which is a smaller, more efficient version of `full`, for the other players in a 3+ battle, and `tiny`, which shows very, very limited data but is a lot faster)

Before, tinymode would kick in in a game of 10+ players, but I'm bumping that to 5+ now, unless you're not playing.

Hopefully this'll help the issue. I'm leaving it open for now. Once the patch is out, if there's still similar lag, please attach a performance profile (you can make one in Chrome's F12 menu), so I can see what's going on (as I cannot reproduce it myself)

**Comment by mat1jaczyyy** [comment] 2020-02-08 20:35
The issue isn't exactly low fps over a period of time, it's more so a spike of 200ish ms where no frames are rendered at all. Right before that fps is stable and same after

**Comment by o5k** [comment] 2020-02-08 20:56
Wumbotize said his issue got better when he turned on "Always simplify multiplayer thumbnails", which enforces `tiny` for all amounts of players. Unless I'm mistaken and another issue popped up later?

**Comment by mat1jaczyyy** [comment] 2020-02-08 21:05
Wumbotize has a relatively weak PC, so he might have been having actual FPS drops while streaming. He's on a 6-7 year old GPU iirc (I remember him barely being able to run TE while streaming) with no GPU video encoding so his CPU is pretty taxed as well.

Either way, I'll try doing that and see if I notice any differences.

**Comment by o5k** [comment] 2020-02-09 20:50
Another thing to try is zomming in, as it lowers the resolution the game renders at.

**Comment by o5k** [comment] 2020-04-30 00:43
Closing as this is just a generic lag issue. If anyone is running into this, please follow https://tetr.io/about/performance/

**Closed by o5k** 2020-04-30 00:43 UTC
Labels: bug, feat: multi, needs-info
