### ISSUE TITLE
Game goes out of focus on ad refreshes

### ISSUE THREAD

**Issue by MarshallJDem** [o5k/tetrio-issues#1377] opened 2024-09-04 03:10 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Desktop

### Describe the bug/issue

While playing zen mode, when the ads refresh and new ads take their place, the game will often go out of focus, and require me to click back in to continue playing. Additionally sometimes there will be 2-3 seconds of stuttering lag as it appears to be loading the new ads. 

It often feels like the ads are being loaded synchronously instead of async or something. 

### Reproducing

Just run a game of zen mode and play while waiting for ads to refresh. Happens like 50% of the time for me. 

### Expected behavior

Seemless gameplay that isn't interrupted by ad changes.

**Comment by aymak91** [comment] 2024-09-04 04:52
I encounter the same bug except during the Zenith Tower. I was wondering why I kept going out of focus and dying before I realized the ads were basically making it unplayable.

**Comment by ZaptorZap** [comment] 2024-09-04 06:49
Duplicate of https://github.com/tetrio/issues/issues/994

**Closed as not planned by ZaptorZap** 2024-09-04 06:49 UTC
Labels: bug, duplicate
