### ISSUE TITLE
Ads sitting on top of hold box during game play

### ISSUE THREAD

**Issue by mlecoz** [o5k/tetrio-issues#1317] opened 2024-07-04 20:05 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Ventura 13.2.1

### Browser and version

Chrome 126.0.6478.62

### Describe the bug/issue

Ad sits on top of my hold box during game play so that I cannot see what I am holding. I tried zooming out (Cmd -) on the browser, which worked for a bit, until the ads changed. Then the new ad was on top of my board! At that point I quit the game in frustration. The other annoying thing is that when I hit "x" on the ad, tetr.io tells me I'm out of focus, presumably because that little ad is another window, I would imagine. But it's an annoying extra step to have to click the tetr.io window again to get back to gameplay.

### Expected behavior

Ads do not obscure game board or holds box.

**Comment by ZaptorZap** [comment] 2024-07-05 02:02
Duplicate of https://github.com/tetrio/issues/issues/1122

**Closed as not planned by ZaptorZap** 2024-07-05 02:02 UTC
Labels: bug, duplicate
