### ISSUE TITLE
The need for a Pause Button

### ISSUE THREAD

**Issue by ghost** [o5k/tetrio-issues#1256] opened 2024-01-26 18:25 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I find it frustrating when I'm playing in Solo Zen mode and there is no pause button. Sometimes I play Zen mode while focusing on a video, before class starts, etc. If I have to leave or pay attention to something, I always have to just leave the tab or go into the game settings to turn gravity off. If I have leveling on, I make mistakes while trying to get it to stop for a moment. 

### Describe the solution you'd like

All I really want to see is for there to be a pause button present on the game screen.

### Describe alternatives you've considered

There really is no alternative

**Comment by ZaptorZap** [comment] 2024-01-26 18:26
Duplicate of #223

**Closed as not planned by ZaptorZap** 2024-01-26 18:26 UTC
Labels: improvement, duplicate
