### ISSUE TITLE
TETR.IO goes loading forever

### ISSUE THREAD

**Issue by MrChutaGMD** [o5k/tetrio-issues#1330] opened 2024-07-27 16:44 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Google Chrome/Version 126.0.6478.185 (Official Build) (64-bit)

### Describe the bug/issue

when i enter the page, tetrio finishes downloading the assets but gets stuck on the loading screen.

https://github.com/user-attachments/assets/06eb881c-33d0-4b47-9c9c-57a3cfc2cc9b

### Reproducing

1. go to tetr,io
2. make an account and join, if you dont have one
3. close tetrio
4. join again
5. enjoy your bug

### Expected behavior

go to the menu screen when i join i guess

### Console logs

![image](https://github.com/user-attachments/assets/e6aaca2c-3dc0-467d-8e38-c20fb7be3e53)

uhh i think this works here right?

### Additional context

i cant run tetrio desktop so i use the website instead by the way

**Comment by ZaptorZap** [comment] 2024-07-27 17:23
Duplicate of #1329

**Closed as not planned by ZaptorZap** 2024-07-27 17:23 UTC
Labels: bug, duplicate
