### ISSUE TITLE
Doesn't work in Firefox

### ISSUE THREAD

**Issue by Daniel15** [o5k/tetrio-issues#179] opened 2020-03-22 06:57 UTC
### Describe the bug/issue
After configuring the game, I just get a blank page

### Reproducing
Solo -> 40 lines -> Start

### Expected behavior
It should work

### Screenshots
![image](https://user-images.githubusercontent.com/91933/77244158-64b1d600-6bcf-11ea-9191-b9f63b32e80e.png)

### Your setup
 - **OS and version**: Windows 10, 1903
 - **Browser and version**: Firefox 74

### Additional context
Console output:
```
Error: WebGL context was lost. tetrio.js:1:281280
TETR.IO tetrio.js:23:52677
Please be careful when pasting anything in the console. Attackers may be out to steal your login information. tetrio.js:23:52956
Up to date. Local version 1.0.0-production | Commit 1aeffd9 (3/21/2020, 1:26:18 PM) | Server cycle OSO3K9yUv | Build 5Neb5jlY6 (3/21/2020, 1:26:36 PM) | PID 6822 tetrio.js:23:58889
Error: WebGL context was lost. 2 tetrio.js:1:281280
Error: WebGL warning: drawElementsInstanced: Tex image TEXTURE_2D level 0 is incurring lazy initialization. tetrio.js:1:227357
```

**Comment by o5k** [comment] 2020-03-22 13:33
Can you please open DxDiag (Win-R, then type `dxdiag`, then save all data as file), and send me the DxDiag,txt in private?

**Comment by Daniel15** [comment] 2020-03-23 02:37
Hey @o5k, here's the [DxDiag.txt](https://github.com/o5k/tetrio-issues/files/4366947/DxDiag.txt).
This was on my laptop - it's a Lenovo X1 Extreme that I have connected to a ThinkPad Thunderbolt 3 Workstation Dock with two screens attached (a BenQ BL3200PT and a Dell U3014), both via DisplayPort.

**Comment by o5k** [comment] 2020-03-23 13:50
Hmmm, specs shouldn't be an issue here. I can see there was an error for firefox, maybe restart your PC and try again? The console message tells me Firefox has decided to take away the GPU context.. :/

**Comment by Cublex** [comment] 2020-03-28 02:02
Can't reproduce, just got a fresh install of Firefox (latest version) and it works fine. Also a good reminder that I suck at 40L

**Comment by o5k** [comment] 2020-04-30 00:45
Closing until more info arises, thousands of users seem to be using it fine so idk

**Closed by o5k** 2020-04-30 00:45 UTC
Labels: bug, needs-info
