### ISSUE TITLE
Stat-based Matchmaking

### ISSUE THREAD

**Issue by LuwuVelasco** [o5k/tetrio-issues#1309] opened 2024-06-14 04:11 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Chrome Versión 126.0.6478.56

### Describe the bug/issue

The matching games of Tetra League are unfair. It pairs you with people whose PPS is higher than yours.

### Expected behavior

The matching games of Tetra League should pair you with people whose PPS is equal or nearer than yours (not more than 0.1 or less).

### Screenshots

![image](https://github.com/tetrio/issues/assets/105027435/49136f6a-c1f1-4771-8cd7-5cd6e7ed5d1e)

**Comment by ZaptorZap** [comment] 2024-06-14 04:22
This is effectively a duplicate of [#1160](https://github.com/tetrio/issues/issues/1160#issuecomment-1630328139). I'm not reiterating the extent of the arguments from related conversations, but this is an ill-advised feature request. I would advise you to **report** massive outliers, such as the one featured in your screenshot, as they are simply circumventing matchmaking independently, which is against [TETR.IO's rules](https://tetr.io/about/rules/#r2)—stat based matchmaking **can not fix this**. TETR.IO uses the [Glicko-2](https://en.wikipedia.org/wiki/Glicko_rating_system#Glicko-2_algorithm) industry standard.

**Closed as not planned by ZaptorZap** 2024-06-14 04:22 UTC
Labels: improvement, wontfix, feat: league
