### ISSUE TITLE
Opponent thumbnails appear over your own board in big games.

### ISSUE THREAD

**Issue by Lekrkoekj** [o5k/tetrio-issues#184] opened 2020-03-22 20:55 UTC
### Describe the bug/issue
Opponent thumbnails appear over your own board in big games.

### Reproducing
1. Go to Quick Play.
2. Enter a game and wait for it to start.

### Expected behavior
They should be under your own board or next to it.

### Screenshots
https://i.imgur.com/0Kd1jg6.jpg
https://i.imgur.com/XNpMX7R.jpg
https://i.imgur.com/A9q2SA1.png

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Microsoft Edge Chromium 82

### Additional context
-

**Comment by o5k** [comment] 2020-03-22 21:15
Duplicate of #176 .

**Closed by o5k** 2020-03-22 21:15 UTC
Labels: bug
