### ISSUE TITLE
Add an option to remove SZ starts

### ISSUE THREAD

**Issue by ray1i** [o5k/tetrio-issues#186] opened 2020-03-23 23:15 UTC
Whenever the first two pieces in 40L are S and Z I just restart anyway, so having the option to disable them entirely would just be a nice quality of life improvement. Maybe it could be added to the custom menu. I know Nullpomino and Jstris already do this automatically.

**Comment by o5k** [comment] 2020-03-23 23:17
Duplicate of #71

**Closed by o5k** 2020-03-23 23:17 UTC
Labels: duplicate, improvement
