### ISSUE TITLE
Tetris fields still zooming into frame if you tab in as game starts

### ISSUE THREAD

**Issue by Kully** [o5k/tetrio-issues#285] opened 2020-04-26 16:59 UTC
### Describe the bug/issue
If a game of Tetra League game is about to start and you are on another tab, and you switch back to the tetris.io tab, the 2 playfields (the 10X18 fields where the blocks live) will still be zooming into view, and the game will be playable/live while zooming, making the pieces small.

NB I read skimmed through most of issues and it make be related to [this one](https://github.com/o5k/tetrio-issues/issues/252)
 
### Reproducing
1. enter Tetra League mode
2. click 'enter matchmaking'
3. tab off the current tab
4. wait until the match is about to start - after hearing ~3 of the 5 count down sfx, tab into the tetris.io tab
5. observe

### Expected behavior
The zoom animation should have been triggered at the same time as if you were looking at the active tab the whole time. This means the tetris playfields should be nearly in their final place so you can have the full screen as you begin to play.

### Screenshots

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10369095/80313993-8b5dc080-87bc-11ea-83fa-58a9e26c8b23.gif)

### Your setup
 - **OS and version**: Mac OS X 10.13.3 (High Sierra)
 - **Browser and version**: Chrome Version 81.0.4044.122 (Official Build) (64-bit)

### Additional context
no console logs changes when i switched over the tabs

Hope this was helpful and informative. 🍰

**Comment by o5k** [comment] 2020-04-27 20:40
Duplicate of #229

**Closed by o5k** 2020-04-27 20:40 UTC
Labels: bug
