### ISSUE TITLE
Option to Prevent Accidental "Instant Soft Drop" (Max SDF Soft Drop, aka Sonic Drop)

### ISSUE THREAD

**Issue by SphyxDev** [o5k/tetrio-issues#1263] opened 2024-02-23 18:50 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

When I play with Max SDF and soft drop a piece, I sometimes find myself accidentally soft dropping the ***next*** piece all the way down as well, since I sometimes keep the soft drop button held down as the piece locks in. This often results in an undesired piece landing in an undesired spot. It usually locks in before I can even react, or is straight up impossible to get out of that spot.

### Describe the solution you'd like

There's already a "Prevent Accidental Hard Drops" option. So, in a similar fashion, there could be a "Prevent Accidental Soft Drops" option (or something along those lines) that puts a few frames of delay to the soft drop every time a new piece spawns in.

This option would be off by default as the default SDF is not infinite, and the problem only really exists when the soft drop acts as a sonic drop.

### Describe alternatives you've considered

None.

### Video Clip Demonstrating the Issue
https://github.com/tetrio/issues/assets/153221885/5915b688-1efb-4cc3-b990-4213fbb4f550

**Comment by ZaptorZap** [comment] 2024-02-23 19:06
Duplicate of #901

**Closed as not planned by ZaptorZap** 2024-02-23 19:06 UTC
Labels: improvement, duplicate
