### ISSUE TITLE
Piece moves to the side if i hold left or right on my keyboard.

### ISSUE THREAD

**Issue by FruitLoopsLab** [o5k/tetrio-issues#254] opened 2020-04-11 14:52 UTC
When I move left or right sometimes it keeps going if I let it go.

I expect it to be like jstris where its smooth and goes with my inputs.

### Your setup
Im using Windows 10 with Microsoft Edge

**Comment by 020m** [comment] 2020-04-11 18:58
There's a similar issue already reported here #181

**Comment by o5k** [comment] 2020-04-11 19:07
Duplicate of #181

**Closed by o5k** 2020-04-11 19:07 UTC
Labels: bug
