### ISSUE TITLE
Stuck on splash screen, infinite loading

### ISSUE THREAD

**Issue by BlandBread** [o5k/tetrio-issues#1331] opened 2024-07-27 16:54 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome + desktop 9

### Describe the bug/issue

game has been loading for the past hour. have had multiple reloads by now, and deleting the app and downloading again.
the game just keeps getting stuck loading.

### Reproducing

Open tetr.io on browser, log in.
Download the app, open it.

### Expected behavior

Open the game.
Log into game.
Play.

### Screenshots

![image](https://github.com/user-attachments/assets/4b60180f-e7f3-4c97-8d5a-0b9a40a81710)
![image](https://github.com/user-attachments/assets/d90a9100-b553-441b-8e9c-b0c3051d90f0)

### Additional context

Other people have had this issue as well. The player count hasn't risen back to its peak on the status page either, suggesting even more people having this issue.

**Comment by ZaptorZap** [comment] 2024-07-27 17:23
Duplicate of #1329

**Closed as not planned by ZaptorZap** 2024-07-27 17:23 UTC
Labels: bug, duplicate
