### ISSUE TITLE
Handicapped game option for players with skill gaps to have fun together

### ISSUE THREAD

**Issue by Makinatsuki** [o5k/tetrio-issues#1367] opened 2024-08-19 05:24 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I've seen a lot of players wanting to engage in 1v1 with other people in the Discord server, or in the global chat, but a lot of the time they'd get an unbalanced matchup with someone else, myself being one of the weaker player at times. I wanted to propose a possible solution to this issue. It's not that big of an issue since you can just enter Quick Play or Tetra League to find some challenge, but this feature is meant for having fun with friends you know.

### Describe the solution you'd like

Based on the TR difference (or on the xp level difference if Tetra League is not currently active), the board of one player will change accordingly to accomodate for the skill difference. The weaker player's board will get taller to allow them to tank more garbage without topping out and give them more room to maneuver their pieces. Or the board could also be narrowed down to increase their combo potential. For the stronger player, the opposite would be applied. But I'd suggest priortizing increasing their board width over decreasing their board height because at some point, the stronger player would become too easy to be topped out, even by inexperienced players. I'd say let the limit of the board height range from 8 to 100 and the limit of the board width from 10 to 30. Further adjustments can be made during the process of testing the feature out. Maybe start with making the feature exclusive to 1v1 in its beta phase and then make some changes to make it compatible with more than 2 players?

### Describe alternatives you've considered

I've seen a lot of people taking different approaches to handicapping themselves when playing a weaker player, such as limiting their pps to a certain threshold or straight up taking turns placing the tetrominoes, which could get boring real quick for the stronger player due to having to wait for the weaker player to make their move. Disabling holding changes how Tetris is played fundamentally and I don't like that, personally.

**Comment by ZaptorZap** [comment] 2024-08-19 05:51
Duplicate of #288

**Closed as not planned by ZaptorZap** 2024-08-19 05:51 UTC
Labels: improvement, duplicate
