### ISSUE TITLE
sonic drop when using ARS

### ISSUE THREAD

**Issue by tohumaster69420** [o5k/tetrio-issues#251] opened 2020-04-10 10:31 UTC
as someone who likes to play tetris the grand master 3, i like to use ARS when playing. so when i tried to play tetr.io solo mode with ARS, i was quite annoyed at the exclusion of the sonic drop, as i noticed it was replaced with the hard drop. this put me off my game quite a bit as i was used to being able to control the blocks after using a sonic drop, something you can't do with hard drop

**Comment by Wirtualnosc** [comment] 2020-04-10 13:35
I'd argue it's just better to have it as a separate option, to allow for sonic drop outside ARS as well; see #203

**Comment by o5k** [comment] 2020-04-11 15:44
Duplicate of #203 .

**Closed by o5k** 2020-04-11 15:44 UTC
Labels: improvement
