### ISSUE TITLE
Near Full Screen Intrusive Ad

### ISSUE THREAD

**Issue by Canti510** [o5k/tetrio-issues#1427] opened 2024-11-25 03:38 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Desktop Client

### Describe the bug/issue

Disruptive large ad

### Expected behavior

No ads to impede on game board. Ads to be low memory and non-intrusive

### Screenshots

![TETR IO_XAGHpmR5Pz](https://github.com/user-attachments/assets/662e2b4a-839d-49b5-96cc-bfd057d50b0b)

### Console logs

![TETR IO_BtsilfZFls](https://github.com/user-attachments/assets/af054cd9-08a7-4fb1-b9db-6ca12bfb31f8)

**Comment by ZaptorZap** [comment] 2024-11-25 04:55
Duplicate of #1425

**Closed as not planned by ZaptorZap** 2024-11-25 04:55 UTC
Labels: bug, duplicate
