### ISSUE TITLE
not able to load, stuck on loading screen

### ISSUE THREAD

**Issue by quackadillyblip** [o5k/tetrio-issues#1329] opened 2024-07-27 16:14 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

windows 11

### Browser and version

9.0.0

### Describe the bug/issue

did a reinstall after previous version no longer loaded.
unistalled, got a fresh download, installed.
launching app shows the splash-screen and my gpu goes beast-mode.

![Naamloos](https://github.com/user-attachments/assets/cf503698-8d2e-494d-89b5-9e016248bc8d)

app seems completely broken, i could play in browser, but then i disconnect every other minute

### Expected behavior

open the app
play

### Screenshots

![image](https://github.com/user-attachments/assets/304261f7-8051-4aad-a86f-83d507675d3e)

### Console logs

![image](https://github.com/user-attachments/assets/fc642dee-38ac-47e5-ba90-a52c6675f288)

**Comment by quackadillyblip** [comment] 2024-07-27 16:30
also found this: 
![image](https://github.com/user-attachments/assets/3afef421-17e0-4e95-b75a-0eb7f4c3b632)


when i clear site storage in dev mode, i can restart and log in, but then the app lags...
i can barely set graphics to minimal but after a restart i'm back stuck on the splash

**Comment by BlandBread** [comment] 2024-07-27 16:42
Same issue. played for around 1 minute, then got disconnected and am now stuck on the splash on desktop, and on browser am stuck after logging in

**Comment by BlandBread** [comment] 2024-07-27 16:44
expected behaviour:
open the app
play and fill the void in my soul

**Comment by BlandBread** [comment] 2024-07-27 16:45
something else i should mention: both versions have been stuck there for an hour

**Comment by boiiseuskera** [comment] 2024-07-27 17:05
Maybe uninstall the app on Control Panel and then install it again through a new copy of the TETR.IO installer? It worked for me, even tho now I have to reinstall it every time I try to open it for it to open properly

**Comment by quackadillyblip** [comment] 2024-07-27 17:11
> Maybe uninstall the app on Control Panel and then install it again through a new copy of the TETR.IO installer? It worked for me, even tho now I have to reinstall it every time I try to open it for it to open properly

yes, tried this... then came here to post bug report

**Comment by boiiseuskera** [comment] 2024-07-27 17:13
> > Maybe uninstall the app on Control Panel and then install it again through a new copy of the TETR.IO installer? It worked for me, even tho now I have to reinstall it every time I try to open it for it to open properly
> 
> yes, tried this... then came here to post bug report

I have seen your issue and I understand it is not working for you but I was talking to BlandBread

**Comment by quackadillyblip** [comment] 2024-07-27 17:19
> > > Maybe uninstall the app on Control Panel and then install it again through a new copy of the TETR.IO installer? It worked for me, even tho now I have to reinstall it every time I try to open it for it to open properly
> > 
> > 
> > yes, tried this... then came here to post bug report
> 
> I have seen your issue and I understand it is not working for you but I was talking to BlandBread

how was i suppose to know that :p ...
excuse me, sir

**Comment by boiiseuskera** [comment] 2024-07-27 17:32
App seems completely hopeless tbh so the best I can suggest is to keep the tetr.io tab open in the background for as long as possible without closing it so you do not have to repeat the process as long as it is open

**Comment by BlandBread** [comment] 2024-07-27 18:05
My computer's gonna nuke doing that, I left it like that and it hibernated after I walked my dog

**Comment by boiiseuskera** [comment] 2024-07-27 18:30
> My computer's gonna nuke doing that, I left it like that and it hibernated after I walked my dog

Have u tried deleting it through the Control Panel and then reinstalling through TETR.IO Setup again?

**Comment by BlandBread** [comment] 2024-07-27 18:35
I should try that later

**Comment by BlandBread** [comment] 2024-07-27 20:57
> > My computer's gonna nuke doing that, I left it like that and it hibernated after I walked my dog
> 
> Have u tried deleting it through the Control Panel and then reinstalling through TETR.IO Setup again?

so funny story, i did that and it worked. my browser is still very much f ed but yea

**Comment by BlandBread** [comment] 2024-07-27 21:09
> Have u tried deleting it through the Control Panel and then reinstalling through TETR.IO Setup again?
>> so funny story...

basically my thing is broken. again. it lagged. a lot. i had to restart it when it was on low graphics to turn on "minimal graphics". it got stuck. again. eugggh

**Comment by BlandBread** [comment] 2024-07-27 21:33
so, temp fix.
reinstall the game every fing time you wanna play it.
browser players im sorry

**Comment by ZaptorZap** [comment] 2024-07-27 21:42
Ok, so the HTTP `431` implies that your browser is sending malformed request headers. I believe this is because of some sort of cookie corruption. You should try completely clearing cookies before resigning to never playing tetr​.io again or whatever.

**Comment by BlandBread** [comment] 2024-07-27 21:51
> Ok, so the HTTP `431` implies that your browser is sending malformed request headers. I believe this is because of some sort of cookie corruption. You should try completely clearing cookies before resigning to never playing tetr​.io again or whatever.

I am still using the "temp fix" I mentioned. I will try this.

**Comment by BlandBread** [comment] 2024-07-27 21:52
![17221171357269190844589257106911](https://github.com/user-attachments/assets/d21248f6-69c9-46ce-9d04-b4112c3dd8be)
Love from loading screen

**Comment by BlandBread** [comment] 2024-07-27 21:58
most of my console is filled with this
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

**Comment by o5k** [comment] 2024-07-27 23:38
Fixed in upcoming patch.

**Closed as completed by o5k** 2024-07-27 23:38 UTC
Labels: bug

**Comment by BlandBread** [comment] 2024-07-27 23:40
<3 thx

**Comment by midvightmirage** [comment] 2026-01-17 16:20
Is not fixed, after minutes still at 9/34 textures.
