### ISSUE TITLE
allow setting DAS more precisely

### ISSUE THREAD

**Issue by LastExceed** [o5k/tetrio-issues#72] opened 2020-02-27 13:36 UTC
allow setting the DAS with millisecond precision like in Jstris, or at least half frames like Cultris. There is no point in limiting to 60hz frames when the game is running in real-time

Probably related to #66

**Comment by o5k** [comment] 2020-02-27 14:07
Duplicate of #33

**Closed by o5k** 2020-02-27 14:07 UTC
Labels: improvement
