### ISSUE TITLE
Tabbing back into TETR.IO when just receiving a league match breaks the intro screen

### ISSUE THREAD

**Issue by NikoAndTails** [o5k/tetrio-issues#240] opened 2020-04-07 21:19 UTC
Platform: Windows 10
Browser: Chrome Latest Version

1. queue for tetra league
2. go to another tab
3. 5 seconds after getting the Match Found notification for league, tab back in
4. player intro screen will be blank, only the sound will play until the match intro comes up, at which point it works fine

What this looks like: https://i.imgur.com/hQQ2L3H.png

**Comment by o5k** [comment] 2020-04-08 08:28
Duplicate of #229

**Closed** 2020-04-08 08:29 UTC
Labels: bug, duplicate
