### ISSUE TITLE
The tetrio board is scaled poorly when the widow is not maximized.

### ISSUE THREAD

**Issue by kevinx83** [o5k/tetrio-issues#1306] opened 2024-06-04 02:07 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I usually use my computer split screen so I can see multiple things at once. I always wanted to do this with tetrio but never have since the board scales really poorly when the window isn't maximized. For example, if I shrink the window to have an aspect ratio similar to a phone screen, I would expect the board to perfectly fit but instead it's super zoomed out since it's dependent on the width of the window (i think)

### Describe the solution you'd like

Be able to have the board fit nicely into the window no matter the window height and width

### Describe alternatives you've considered

I have considered using other websites like jstris because of this quality of life issue I have.

**Comment by ZaptorZap** [comment] 2024-06-04 02:16
Duplicate of #458

**Closed as not planned by ZaptorZap** 2024-06-04 02:16 UTC
Labels: improvement, duplicate
