### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by Imissherabusivebehaviour** [o5k/tetrio-issues#1290] opened 2024-04-22 20:34 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome, Ver. 123.0.6312.124 

### Describe the bug/issue

When I was in a competitive game, the screen turned orange around the borders then full-screened an AD. This caused me visual issues making me lose a round, I had it in the loading screen and thought it would only be there but it appeared in-game and I thought it would be weird if u were playing competitive and a screen just blocked your whole view. I would assume this is a bug but if this is a feature please remove it cause I am 100% sure nobody will enjoy this.

### Reproducing

Play a couple matches for 3 rounds in competitive or just go to the website and be signed in.

### Expected behavior

I would expect the ad to not pop-up in the middle of the game, I would assume it would stop and just be a home screen feature.

### Screenshots

N/A

### Console logs

![Screenshot 2024-04-22 133321](https://github.com/tetrio/issues/assets/167816742/e266f4d2-2832-4c74-8a03-499fe28c8917)

### Additional context

I just hope this doesn't happen again I don't want to lose my elo to an AD.

**Comment by ZaptorZap** [comment] 2024-04-23 00:41
Duplicate of #1122

**Closed as not planned by ZaptorZap** 2024-04-23 00:41 UTC
Labels: bug, duplicate
