### ISSUE TITLE
Ghost piece opacity

### ISSUE THREAD

**Issue by steve4ino** [o5k/tetrio-issues#289] opened 2020-04-28 16:47 UTC
### Is your feature request related to a problem? Please describe.
I like having the background visible, but now the ghost piece is a bit hard to see at times.

### Describe the solution you'd like
I would like the ability to change the opacity of the ghost piece in the settings.

### Describe alternatives you've considered
Custom block themes like on jstris.

**Comment by Tenchi2xh** [comment] 2020-04-28 17:00
Duplicate of #279

**Closed** 2020-04-29 12:38 UTC
Labels: improvement
