### ISSUE TITLE
Mobile Version...

### ISSUE THREAD

**Issue by Baggager** [o5k/tetrio-issues#1285] opened 2024-04-11 09:35 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

At study I have enough free time and i wish i could spend it at TETR.IO. But there is no possibility unless my trusty phone could support TETR.IO...

### Describe the solution you'd like

Hello, this is one of probably dumbest suggestions, but... 

Since [TETR.IO](http://tetr.io/) mainly specialises on versus-battles, and original Tetris removed this feature for good(not speaking of Switch), is there possibility that [TETR.IO](http://tetr.io/) will come as Mobile patch or even maybe app in Play Store/for ios? 

If the problem is "how are you going to handle stuff" then its not so complicated, i may even suggest: 

Swipe up = Hold the figure/swap
Left/right swipes = move Tetraminoes
Quick swipe down = Hard drop
Swipe down(+hold on place, without releasing) = soft drop
Left half screen tap = Rotate 90° counter clockwise
Right side tap = Rotate 90° clockwise
180° rotation = double-tap (someone uses this?)

Attacks? Just press on modes. 

But yet, maybe restict people from playing Tetra League or at least warn them, because in my opinion handling on phone and PC really varies.

Maybe its a lot of things to do, but that might rise the online, since I might be not the only who wants to play a match at the work, maybe. Also, not sure if such people exist, playing from mobile might be comfortable for someone (but not me) and new way to handle figure

### Describe alternatives you've considered

I tried emulators, but none help me, taking keyboard/controller with me is cringe, last similar idea was available somewhere in 2019, when Tetris Royale existed.

### Additional context

have a cup of your favorite beverage, you deserve it, my fellow

**Comment by ZaptorZap** [comment] 2024-04-11 10:36
Duplicate of #950

**Comment by ZaptorZap** [comment] 2024-04-11 10:36
I'd recommend reading https://tetrio.github.io/faq/troubleshooting.html#mobile for potential ways to play TETR.IO on mobile. Apologies.

**Closed as not planned by ZaptorZap** 2024-04-11 10:36 UTC
Labels: improvement
