### ISSUE TITLE
1001th place in leaderboards

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#130] opened 2020-03-10 00:25 UTC
whoop
![image](https://user-images.githubusercontent.com/6901295/76268330-b2405180-6265-11ea-83d9-2c40464db442.png)

**Comment by Roxis88** [comment] 2020-03-10 04:07
Hmm... I thought it is not a bug, since it means that "You're not in 1000 fastest, so why I should rank you?" for the rough translate.

**Comment by o5k** [comment] 2020-03-10 09:27
Well no, it's supposed to not show a nth place at all then

**Comment by o5k** [comment] 2020-03-10 09:45
Fixed in next patch.

**Closed by o5k** 2020-03-10 09:45 UTC
Labels: bug
