### ISSUE TITLE
Quick play glitching and becoming unplayable

### ISSUE THREAD

**Issue by Dvrkon** [o5k/tetrio-issues#1365] opened 2024-08-16 19:37 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Newest version for desktop version

### Describe the bug/issue

New quickplay gamemode is unplayable as it says "Out of Focus"
Then the pieces automatically go to either left or right.
This makes the game unplayable

### Expected behavior

Glitch to be resolved and maybe a patch to be released as soon as possible

**Comment by ZaptorZap** [comment] 2024-08-17 00:03
Duplicate of https://github.com/tetrio/issues/issues/994

**Closed as not planned by ZaptorZap** 2024-08-17 00:03 UTC
Labels: bug, duplicate
