### ISSUE TITLE
WEBGL keeps crashing (sometimes with Tetrio) when im in a place where you can change something (like Config)

### ISSUE THREAD

**Issue by Deniiguess** [o5k/tetrio-issues#1353] opened 2024-08-03 21:56 UTC
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Kubuntu

### Browser and version

TETR.IO Desktop V9

### Describe the bug/issue

When im in a place where i can change something (like Config), then after a while an error message appears that WEBGL crashed, if i dont click continue in time then the app also crashes
if i click continue in time, everything works fine after that (WEBGL can still crash after that), only thing i noticed thats wrong was that the tetris pieces were invisible until i placed them

### Reproducing

1. Go to Config
2. Wait a bit
3. Done

### Expected behavior

Not to crash

### Screenshots

![Screenshot_20240803_232038](https://github.com/user-attachments/assets/32ac5515-3237-4f7d-8a62-ad9be45e9cb1)

**Comment by dotSepia** [comment] 2024-08-04 00:05
Happens to me as well, using desktop client on Arch Linux. WebGL mode is on WebGL 2.

**Comment by Deniiguess** [comment] 2024-08-04 00:15
i tried every WEBGL option (Legacy, 1 and 2)

**Comment by CodeObserver21** [comment] 2024-08-04 00:56
WebGL crashes for me too on openSUSE Leap 15.6. I noticed that it only happens whenever my mouse hovers over an item and a tooltip shows. Any tooltip - doesn't need to be in the settings menu. Crash happens regardless of what WebGL I use.

Can anyone confirm if tooltips lead to WebGL crash or is it just me?

**Comment by ZaptorZap** [comment] 2024-08-04 03:52
Using Linux? Try adding `--in-process-gpu` to your launch arguments.

**Comment by ZaptorZap** [comment] 2024-08-04 03:53
Duplicate of #1268

**Closed as not planned by ZaptorZap** 2024-08-04 03:53 UTC
Labels: bug, duplicate

**Comment by Deniiguess** [comment] 2024-08-04 09:29
oh it seems to crash when i am hovering over something that displays text after a while (stuff in the Config, Custom Game menu, Zen Mode menu, the only 3 things i can confirm that can crash)

**Comment by Deniiguess** [comment] 2024-08-04 10:23
> Using Linux? Try adding `--in-process-gpu` to your launch arguments.

i dont know how to do that

**Comment by ZaptorZap** [comment] 2024-08-04 10:28
If you installed a .deb file, just open a Terminal (`CTRL+Alt+T`? `Alt+F2`?) and run `tetrio-desktop --in-process-gpu`. If it's from the tarball, just open your terminal in the correct folder (right click in the folder in the file explorer, should hopefully be an option) and then run `./tetrio-desktop --in-process-gpu`. You might be able to just edit your shortcut and add `--in-process-gpu` to the target as well.

**Comment by Deniiguess** [comment] 2024-08-04 10:32
okay thank you, i just have to open it when the terminal is in usr/bin and then i type TETR.IO --in-process-gpu
